### ISSUE TITLE
rake route_dog:clean doesn't actually clean

### ISSUE THREAD

**Issue by be9** [zevarito/route_dog#6]
route_dog / lib / tasks / tasks.rake:

```
File.delete("test/mock_app/tmp/route_dog_routes.yml") if File.exists? "test/mock_app/tmp/route_dog_routes.yml"
```

Cleans in the mock app, doesn't clean in real app.

**Comment by zevarito** [comment]
Thanks for reporting it, I will take care.

**Comment by zevarito** [comment]
@be9

I've pushed a fix for this to master, can you try it from there before release a new version? Thanks!
